### ISSUE TITLE
NPM installation directly from GitHub doesn't work due to missing version type

### ISSUE THREAD

**Issue by christopherwk210** [minecraft-addon-tools/minecraft-scripting-types#3]
When using [the yo generator](https://github.com/minecraft-addon-tools/generator-minecraft-addon) I chose TypeScript as my language of choice. Loading up the tsconfig.json and any of the generated .ts files shows an error due to missing types. The package was not found in node_modules, and trying to install it manually shows this error:

![screen shot 2018-12-11 at 6 25 05 am](https://user-images.githubusercontent.com/13367277/49806815-84402a80-fd0d-11e8-9ee3-3ea0ad16125d.png)

I believe a version key has to be added to package.json to remedy this.

**Comment by abc-55** [comment]
Installing from GitHub is no longer possible because we have split the types into multiple packages and use lerna to manage them. To install the types manually use `minecraft-scripting-types-server` and/or `minecraft-scripting-types-client` from npm, e.g. `npm i minecraft-scripting-types-server`.

The genrator should however setup and install everything correctly. Can you provide more information about the errors? What options did you choose when running the generator? What was the content of `package.json` after running the generator?

**Comment by christopherwk210** [comment]
My exact steps and results from the start:
![screen shot 2018-12-11 at 8 37 30 am](https://user-images.githubusercontent.com/13367277/49815177-09343f80-fd20-11e8-9bab-025a9f6824ca.png)

![screen shot 2018-12-11 at 8 37 38 am](https://user-images.githubusercontent.com/13367277/49815176-09343f80-fd20-11e8-969a-c48c1b54d066.png)

The tsconfig.json error:
![screen shot 2018-12-11 at 8 39 23 am](https://user-images.githubusercontent.com/13367277/49815292-4bf61780-fd20-11e8-9f92-d19e58d2dff8.png)

**Comment by christopherwk210** [comment]
I also should mention that I'm developing on a Mac, however I don't think that will have any impact on this.

**Comment by abc-55** [comment]
The reason for the error is that the generator is not yet updated to work with some changes in this repo. @AtomicBlom can you look into this?

As a workaround, you can:
- remove `minecraft-scripting-types` from `package.json`
- `npm i -D minecraft-scripting-types-server`
- `npm i -D minecraft-scripting-types-client`
- remove `"types": ["minecraft-scripting-types"]` from `tsconfig.json`
- add `/// <reference types="minecraft-scripting-types-server" />` to your server files
- add `/// <reference types="minecraft-scripting-types-client" />` to your client files

**Comment by AtomicBlom** [comment]
Sure thing. I'm a little surprised I didn't pick up on this while I was doing my tutorial videos.

**Comment by AtomicBlom** [comment]
Oh, of course I didn't pick it up, I was using JavaScript, not TypeScript derp.

Anyway, fixed now in 0.1.3.
